# Generated by Django 4.0 on 2022-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=155, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='phone number')),
                ('country', models.CharField(choices=[('Bangladesh', 'Bangladesh'), ('India', 'India')], max_length=15, verbose_name='country')),
                ('address', models.CharField(max_length=1000)),
                ('avatar', models.ImageField(default='user/avatar.png', upload_to='avatar/<built-in function id>/')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
